// src/services/profileImage.service.js — Profile picture storage (replaces ProfileImageStorageService.java)
const path = require('path');
const fs = require('fs');
const fsp = require('fs').promises;
const { v4: uuidv4 } = require('crypto');
const sharp = require('sharp');
const logger = require('../utils/logger');

const MAX_IMAGE_DIMENSION = 512;

function getStorageRoot() {
  const dir = path.resolve(process.env.PROFILE_PICTURES_DIR || './uploads/profile-pictures');
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  return dir;
}

function getPublicPath() {
  let uri = (process.env.PROFILE_PICTURES_URI || '/uploads/profile-pictures').trim();
  if (!uri.startsWith('/')) uri = '/' + uri;
  return uri.replace(/\/+$/, '');
}

/**
 * Resize (if needed), store profile image, return public URL.
 * Mirrors ProfileImageStorageService.replaceProfileImage()
 */
async function replaceProfileImage(currentProfilePicture, fileBuffer, mimetype, userId) {
  const storedPath = await storeProfileImage(fileBuffer, mimetype, userId);
  if (isManagedPath(currentProfilePicture)) {
    await deleteManagedFile(currentProfilePicture);
  }
  return storedPath;
}

/**
 * Delete a file if it's a managed path.
 */
async function deleteManagedFile(profilePicture) {
  if (!isManagedPath(profilePicture)) return;
  try {
    const publicPath = getPublicPath();
    const relativeName = profilePicture.substring(publicPath.length + 1);
    const filePath = path.join(getStorageRoot(), relativeName);
    await fsp.unlink(filePath).catch(() => {}); // ignore if not found
  } catch {
    // non-blocking — don't fail the request
  }
}

/**
 * Returns true if the URL was generated by this service.
 */
function isManagedPath(profilePicture) {
  if (!profilePicture) return false;
  return profilePicture.startsWith(getPublicPath() + '/');
}

async function storeProfileImage(fileBuffer, mimetype, userId) {
  if (!fileBuffer || fileBuffer.length === 0) {
    throw new Error('Profile image file is required');
  }
  if (!mimetype || !mimetype.startsWith('image/')) {
    throw new Error('Only image files are allowed for profile pictures');
  }

  // Detect if PNG (has alpha) or convert to jpg
  const sharpInstance = sharp(fileBuffer);
  const metadata = await sharpInstance.metadata();
  const hasAlpha = metadata.hasAlpha;
  const ext = hasAlpha ? 'png' : 'jpg';

  // Resize if needed
  const resized = await sharp(fileBuffer)
    .resize(MAX_IMAGE_DIMENSION, MAX_IMAGE_DIMENSION, {
      fit: 'inside',
      withoutEnlargement: true,
    })
    [hasAlpha ? 'png' : 'jpeg']({ quality: 85 })
    .toBuffer();

  const fileName = `user-${userId}-${generateUuid()}.${ext}`;
  const storageRoot = getStorageRoot();
  const filePath = path.join(storageRoot, fileName);

  await fsp.writeFile(filePath, resized);
  logger.info(`Profile image saved: ${filePath}`);

  return `${getPublicPath()}/${fileName}`;
}

function generateUuid() {
  // Use crypto.randomUUID if available (Node 14.17+), else fallback
  try {
    return require('crypto').randomUUID();
  } catch {
    return Math.random().toString(36).substring(2) + Date.now().toString(36);
  }
}

module.exports = { replaceProfileImage, deleteManagedFile, isManagedPath };
