// src/services/resumeEmail.service.js — Replaces Spring ResumeEmailService.java
const { getTransporter } = require('../config/email');
const resumeExportService = require('./resumeExport.service');
const { sanitizeFilename } = require('../utils/sanitize.utils');
const logger = require('../utils/logger');

const MAIL_FROM = process.env.MAIL_FROM || 'noreply@vita.ai';

/**
 * Export a built resume as PDF or DOCX and send it as an email attachment.
 * Mirrors ResumeEmailService.sendResume()
 */
async function sendResume(builtResume, recipientEmail, format) {
  const transporter = getTransporter();
  if (!transporter) {
    throw new Error(
      'Email sending is not configured. Please set MAIL_ENABLED=true and provide SMTP credentials.'
    );
  }

  let fileBytes, filename, mimeType;

  if ((format || 'PDF').toUpperCase() === 'DOCX') {
    fileBytes = await resumeExportService.exportToDocx(builtResume);
    filename = sanitizeFilename(builtResume.title) + '.docx';
    mimeType = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
  } else {
    fileBytes = await resumeExportService.exportToPdf(builtResume);
    filename = sanitizeFilename(builtResume.title) + '.pdf';
    mimeType = 'application/pdf';
  }

  try {
    await transporter.sendMail({
      from: MAIL_FROM,
      to: recipientEmail,
      subject: `Your Resume: ${builtResume.title}`,
      html: buildEmailBody(builtResume.title),
      attachments: [
        {
          filename,
          content: fileBytes,
          contentType: mimeType,
        },
      ],
    });
    logger.info(`Resume email sent to ${recipientEmail} for resume id=${builtResume.id}`);
  } catch (err) {
    logger.error(`Failed to send resume email: ${err.message}`);
    throw new Error('Failed to send email: ' + err.message);
  }
}

function buildEmailBody(resumeTitle) {
  return `
<html>
  <body style="font-family: Arial, sans-serif; color: #1e293b; background: #f8fafc; padding: 32px;">
    <div style="max-width: 560px; margin: 0 auto; background: #fff; border-radius: 12px; padding: 32px; border: 1px solid #e2e8f0;">
      <h2 style="color: #7c3aed; margin-top: 0;">Your Resume is Ready!</h2>
      <p>Hi there,</p>
      <p>Please find your resume <strong>${resumeTitle}</strong> attached to this email.</p>
      <p>Built with <strong>Vita AI Resume Builder</strong> — optimized for ATS and modern hiring.</p>
      <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 24px 0;" />
      <p style="font-size: 12px; color: #94a3b8;">This email was sent from Vita AI. If you did not request this, please ignore it.</p>
    </div>
  </body>
</html>`;
}

/**
 * Email a pre-rendered PDF buffer generated by Puppeteer.
 */
async function sendResumeBuffer(pdfBuffer, resumeTitle, recipientEmail) {
  const transporter = getTransporter();
  if (!transporter) {
    throw new Error(
      'Email sending is not configured. Please set MAIL_ENABLED=true and provide SMTP credentials.'
    );
  }
  const filename = sanitizeFilename(resumeTitle || 'resume') + '.pdf';
  try {
    await transporter.sendMail({
      from: MAIL_FROM,
      to: recipientEmail,
      subject: `Your Resume: ${resumeTitle}`,
      html: buildEmailBody(resumeTitle),
      attachments: [{ filename, content: pdfBuffer, contentType: 'application/pdf' }],
    });
    logger.info(`Resume PDF email sent to ${recipientEmail} (${filename})`);
  } catch (err) {
    logger.error(`Failed to send resume PDF email: ${err.message}`);
    throw new Error('Failed to send email: ' + err.message);
  }
}

module.exports = { sendResume, sendResumeBuffer };
