cat > /etc/apache2/sites-available/vita.genixpay.com.conf << 'EOF'
<VirtualHost *:80>
    ServerName vita.genixpay.com
    ServerAlias www.vita.genixpay.com

    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteRule ^ https://vita.genixpay.com%{REQUEST_URI} [R=301,L]

    ErrorLog /var/log/apache2/vita.genixpay-http-error.log
    CustomLog /var/log/apache2/vita.genixpay-http-requests.log combined
</VirtualHost>

<VirtualHost *:443>
    SSLEngine On
    SSLProxyEngine On

    SSLCertificateFile /etc/cert/imran/pg.genixpay.com_certificate.crt
    SSLCertificateKeyFile /etc/cert/imran/pg.genixpay.com_key.key
    SSLCACertificateFile /etc/cert/imran/pg.genixpay.com_bundle.ca.crt

    ServerName vita.genixpay.com
    ServerAlias www.vita.genixpay.com

    RequestHeader set X-Forwarded-Proto "https"
    RequestHeader set X-Forwarded-Port "443"
    RequestHeader set X-Forwarded-Host "vita.genixpay.com"

    ProxyPreserveHost On

    ProxyPass /api http://127.0.0.1:5000/api
    ProxyPassReverse /api http://127.0.0.1:5000/api

    ProxyPass / http://127.0.0.1:3000/
    ProxyPassReverse / http://127.0.0.1:3000/

    Timeout 2400
    ProxyTimeout 2400
    ProxyBadHeader Ignore

    ErrorLog /var/log/apache2/vita.genixpay.com-error.log
    CustomLog /var/log/apache2/vita.genixpay.com-requests.log combined
</VirtualHost>
EOF